[config]  
model = "gemini/gemini-2.5-pro-preview-05-06"  
fallback_models = ["gemini/gemini-2.5-pro-preview-05-06"]
response_language = "ja-JP"

[pr_code_suggestions]
commitable_code_suggestions = true # 提案を直接コミット可能な形式にする (GitHubの提案機能)
focus_only_on_problems = false # 問題点だけでなく、より良い書き方などの提案もする
suggestions_score_threshold = 5 # 提案の関連性スコアの閾値 (0-10、低いほど多くの提案)

[github_app]
# PRがオープン、再オープン、レビュー準備完了になった時の自動実行コマンド
handle_pr_actions = ['opened', 'reopened', 'ready_for_review']
pr_commands = [
    "/describe",  # PR作成時に自動で説明を生成
    "/review"     # PR作成時に自動でレビューを開始
    # "/improve"  # PR作成時に自動で改善提案 (多すぎる場合があるので注意)
]

# pushがあった場合 (新しいコミットが追加された場合) の自動実行
handle_push_trigger = true
push_commands = [
    "/review --incremental" # 差分レビューを実行
]

[best_practices]
num_best_practice_suggestions = 2

[auto_best_practices]
# Disable all auto best practices usage or generation
enable_auto_best_practices = true  

# Disable usage of auto best practices file in the 'improve' tool
utilize_auto_best_practices = true 

# Extra instructions to the auto best practices generation prompt
extra_instructions = ""            

# Max number of patterns to be detected
max_patterns = 5                   